package connxt.transaction.dto;

public enum TransactionStatus {
  NEW,
  CREATED,
  HOLD_BALANCE,
  INITIATED,
  PG_ACCEPTED,
  PG_REJECTED,
  REJECTED,
  ABANDONED,
  PG_SUCCESS,
  PG_FAILED,
  PENDING_FOR_APPROVAL,
  APPROVED,
  AUTO_APPROVED,
  SUCCESS,
  FAILED,
  COMPLETED,
  CREDITED_TO_WALLET,
  CLEAR_HELD_BALANCE,
  CANCELLED
}
