/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("build.spring-boot")
}

dependencies {
    // Spring Boot BOM for version management
    implementation(platform(libs.spring.boot.bom))
    
    // Spring Boot starters (versions managed by BOM)
    implementation(libs.bundles.spring.boot.web)
    implementation(libs.bundles.database.jdbc)
}

application {
    // Define the main class for the application.
    mainClass = "nexus.Nexus"
}
