/*
 * This file was generated by the Gradle 'init' task.
 */

import org.gradle.api.tasks.compile.JavaCompile

plugins {
    // Spotless for code formatting
    id("com.diffplug.spotless")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    mavenLocal()
    maven {
        url = uri("https://pkgs.dev.azure.com/tech4jc/_packaging/fynxt-libs/maven/v1")
        val username = System.getenv("FYNXT_LIBS_USERNAME")
        val password = System.getenv("FYNXT_LIBS_PASSWORD")
        if (!username.isNullOrBlank() && !password.isNullOrBlank()) {
            credentials {
                this.username = username
                this.password = password
            }
        }
        mavenContent {
            snapshotsOnly()
        }
    }
}

// Java compilation options to preserve parameter names for reflection
tasks.withType<JavaCompile> {
    options.compilerArgs.add("-parameters")
}

// Spotless configuration for code formatting
spotless {
    java {
        // Use Google Java Format
        googleJavaFormat("1.19.2")
        
        // Import organization
        importOrder(
            "java",
            "javax",
            "org",
            "com",
            "connxt"
        )
        
        // Remove unused imports
        removeUnusedImports()
    }
}
